import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, ChevronDown, Clock3, CreditCard, Heart, MapPin, Minus, Plus, Search, ShoppingBag, Smartphone, Sparkles, Star, Store, UserRound, Utensils, X } from "lucide-react";

type MenuItem = { id: string; name: string; description: string; price: number; vegetarian: boolean; image: string };
type Restaurant = { id: string; name: string; neighborhood: string; cuisine: string; rating: string; time: string; tag: string; image: string; menu: MenuItem[] };
type Profile = { name: string; password: string; mobile: string; email: string; address: string; deliveryTime: string; emailVerified: boolean; phoneVerified: boolean };
type PaymentMethod = "card" | "upi" | "cash";

const foodImages = {
  biryani: "/food/biryani.jpg",
  dosa: "/food/dosa.jpg",
  thali: "/food/thali.jpg",
  burger: "/food/burger.jpg",
  pizza: "/food/pizza.jpg",
};
const dishImages = {
  chickenBiryani: "https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=800&q=85",
  paneerBiryani: "https://images.unsplash.com/photo-1631515242808-497c3fbd3972?auto=format&fit=crop&w=800&q=85",
  chickenBoneless: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=85",
  andhraMeals: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=800&q=85",
  paneerPepperFry: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=85",
  ravaIdli: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=85",
  masalaDosa: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=85",
  cheeseBurger: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=85",
  vegBurger: "https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=800&q=85",
  chickenKebab: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=85",
  naanPaneer: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=800&q=85",
  margherita: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=85",
  chickenPesto: "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=800&q=85",
  hyderabadiBiryani: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=85",
  mushroomBiryani: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=85",
  setDosa: "https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=800&q=85",
  bisibeleBath: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=85",
  dalMakhani: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=85",
  tandooriChicken: "https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2d?auto=format&fit=crop&w=800&q=85",
  butterChicken: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=85",
  loadedVegBurger: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=85",
  chocolateDessert: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=85",
  hotFudge: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=85",
  shawarma: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=85",
  falafel: "https://images.unsplash.com/photo-1593001872095-7d5b3868dd4c?auto=format&fit=crop&w=800&q=85",
  fourCheese: "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=800&q=85",
  pepperoni: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=85",
};

const restaurants: Restaurant[] = [
  { id: "meghana", name: "Meghana Foods", neighborhood: "Indiranagar", cuisine: "Andhra · Biryani", rating: "4.6", time: "32 min", tag: "Bestseller", image: foodImages.biryani, menu: [{ id: "m1", name: "Chicken Biryani", description: "Aromatic basmati rice, tender chicken and Meghana's signature masala.", price: 289, vegetarian: false, image: dishImages.chickenBiryani }, { id: "m2", name: "Paneer Biryani", description: "Fragrant rice layered with spiced paneer and fried onions.", price: 249, vegetarian: true, image: dishImages.paneerBiryani }, { id: "m3", name: "Chicken Boneless", description: "Andhra-style boneless chicken tossed in a fiery masala.", price: 329, vegetarian: false, image: dishImages.chickenBoneless }] },
  { id: "nagarjuna", name: "Nagarjuna", neighborhood: "Residency Road", cuisine: "Andhra · Meals", rating: "4.5", time: "38 min", tag: "Iconic since 1984", image: foodImages.thali, menu: [{ id: "n1", name: "Nagarjuna Special Meals", description: "Unlimited Andhra thali with rice, curries, rasam and dessert.", price: 320, vegetarian: false, image: dishImages.andhraMeals }, { id: "n2", name: "Paneer Pepper Fry", description: "Peppery paneer with curry leaves and roasted spices.", price: 260, vegetarian: true, image: dishImages.paneerPepperFry }] },
  { id: "mtr", name: "MTR 1924", neighborhood: "Lalbagh Road", cuisine: "South Indian · Vegetarian", rating: "4.7", time: "27 min", tag: "Pure veg", image: foodImages.dosa, menu: [{ id: "t1", name: "Rava Idli", description: "MTR's famous steamed semolina idli with ghee and chutney.", price: 95, vegetarian: true, image: dishImages.ravaIdli }, { id: "t2", name: "Masala Dosa", description: "Golden dosa, potato palya, sambar and coconut chutney.", price: 145, vegetarian: true, image: dishImages.masalaDosa }] },
  { id: "truffles", name: "Truffles", neighborhood: "Koramangala", cuisine: "Burgers · American", rating: "4.6", time: "35 min", tag: "20% off", image: foodImages.burger, menu: [{ id: "f1", name: "All American Cheese Burger", description: "Grilled patty, cheddar, lettuce, tomato and house sauce.", price: 295, vegetarian: false, image: dishImages.cheeseBurger }, { id: "f2", name: "Veg Extravaganza Burger", description: "Crispy veg patty, cheese, jalapenos and signature sauce.", price: 245, vegetarian: true, image: dishImages.vegBurger }] },
  { id: "empire", name: "Empire Restaurant", neighborhood: "Brigade Road", cuisine: "North Indian · Kebabs", rating: "4.4", time: "30 min", tag: "Late night", image: foodImages.thali, menu: [{ id: "e1", name: "Empire Chicken Kebab", description: "Char-grilled chicken marinated in warm Indian spices.", price: 280, vegetarian: false, image: dishImages.chickenKebab }, { id: "e2", name: "Butter Naan & Paneer", description: "Soft butter naan with creamy paneer gravy.", price: 230, vegetarian: true, image: dishImages.naanPaneer }] },
  { id: "chianti", name: "Chianti", neighborhood: "St. Marks Road", cuisine: "Italian · Pizza", rating: "4.5", time: "41 min", tag: "Free delivery", image: foodImages.pizza, menu: [{ id: "c1", name: "Margherita Pizza", description: "San Marzano tomato, fresh mozzarella, basil and olive oil.", price: 420, vegetarian: true, image: dishImages.margherita }, { id: "c2", name: "Chicken Pesto Pizza", description: "Roasted chicken, basil pesto, mozzarella and cherry tomato.", price: 510, vegetarian: false, image: dishImages.chickenPesto }] },
  { id: "biriyani-zone", name: "Biryani Zone", neighborhood: "HSR Layout", cuisine: "Biryani · Mughlai", rating: "4.3", time: "34 min", tag: "Combo meals", image: foodImages.biryani, menu: [{ id: "bz1", name: "Hyderabadi Chicken Biryani", description: "Long-grain rice, slow-cooked chicken and saffron-spiced gravy.", price: 259, vegetarian: false, image: dishImages.hyderabadiBiryani }, { id: "bz2", name: "Mushroom Biryani", description: "Basmati rice, roasted mushrooms and fragrant whole spices.", price: 219, vegetarian: true, image: dishImages.mushroomBiryani }] },
  { id: "udupi", name: "Udupi Garden", neighborhood: "BTM Layout", cuisine: "South Indian · Vegetarian", rating: "4.4", time: "25 min", tag: "Pure veg", image: foodImages.dosa, menu: [{ id: "u1", name: "Set Dosa", description: "Three soft dosas with vegetable saagu and coconut chutney.", price: 120, vegetarian: true, image: dishImages.setDosa }, { id: "u2", name: "Bisibele Bath", description: "Classic Karnataka rice-lentil bowl with ghee and boondi.", price: 135, vegetarian: true, image: dishImages.bisibeleBath }] },
  { id: "saarangi", name: "Saarangi", neighborhood: "Whitefield", cuisine: "North Indian · Kebabs", rating: "4.5", time: "42 min", tag: "Chef special", image: foodImages.thali, menu: [{ id: "s1", name: "Dal Makhani", description: "Slow-simmered black lentils finished with butter and cream.", price: 245, vegetarian: true, image: dishImages.dalMakhani }, { id: "s2", name: "Tandoori Chicken", description: "Yogurt-marinated chicken roasted in the tandoor.", price: 385, vegetarian: false, image: dishImages.tandooriChicken }] },
  { id: "social", name: "Social", neighborhood: "Church Street", cuisine: "Café · Continental", rating: "4.4", time: "36 min", tag: "Trending", image: foodImages.burger, menu: [{ id: "so1", name: "Social Butter Chicken", description: "Creamy tomato butter chicken with toasted naan.", price: 340, vegetarian: false, image: dishImages.butterChicken }, { id: "so2", name: "Loaded Veg Burger", description: "Crispy vegetable patty, lettuce and smoky house sauce.", price: 280, vegetarian: true, image: dishImages.loadedVegBurger }] },
  { id: "corner-house", name: "Corner House Ice Cream", neighborhood: "Jayanagar", cuisine: "Desserts · Ice Cream", rating: "4.8", time: "22 min", tag: "Sweet fix", image: foodImages.burger, menu: [{ id: "ch1", name: "Death By Chocolate", description: "Chocolate ice cream, brownie, sauce and chocolate flakes.", price: 220, vegetarian: true, image: dishImages.chocolateDessert }, { id: "ch2", name: "Hot Chocolate Fudge", description: "Vanilla ice cream, warm fudge and roasted nuts.", price: 195, vegetarian: true, image: dishImages.hotFudge }] },
  { id: "karama", name: "Karama Restaurant", neighborhood: "Frazer Town", cuisine: "Arabian · Kebabs", rating: "4.5", time: "39 min", tag: "Family feast", image: foodImages.thali, menu: [{ id: "k1", name: "Chicken Shawarma Plate", description: "Charcoal chicken, hummus, pita and garlic sauce.", price: 310, vegetarian: false, image: dishImages.shawarma }, { id: "k2", name: "Falafel Platter", description: "Crisp falafel with hummus, salad and warm pita.", price: 260, vegetarian: true, image: dishImages.falafel }] },
  { id: "onyx", name: "The Fat Chef", neighborhood: "Malleshwaram", cuisine: "Pizza · Italian", rating: "4.6", time: "33 min", tag: "New on Foodflow", image: foodImages.pizza, menu: [{ id: "fc1", name: "Four Cheese Pizza", description: "Mozzarella, parmesan, cheddar and blue cheese on a crisp base.", price: 460, vegetarian: true, image: dishImages.fourCheese }, { id: "fc2", name: "Pepperoni Pizza", description: "Spiced pepperoni, mozzarella and oregano.", price: 520, vegetarian: false, image: dishImages.pepperoni }] },
].map((restaurant) => ({ ...restaurant, image: restaurant.id === "meghana" ? foodImages.biryani : restaurant.menu[0]?.image ?? restaurant.image }));

const categories = [["All", "✦"], ["Biryani", "🍛"], ["Pizza", "🍕"], ["South Indian", "🥘"], ["Burgers", "🍔"], ["Desserts", "🍰"]];
const portalSlides = [
  { image: foodImages.biryani, alt: "Biryani ready to order", label: "Biryani nights" },
  { image: foodImages.dosa, alt: "Crisp masala dosa", label: "South Indian classics" },
  { image: foodImages.pizza, alt: "Freshly baked pizza", label: "Pizza, freshly baked" },
  { image: foodImages.burger, alt: "Juicy burger ready to serve", label: "Burgers worth sharing" },
  { image: foodImages.thali, alt: "A colorful Indian thali", label: "A table full of comfort" },
  { image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=960&q=85", alt: "Fresh grain bowl with greens", label: "Bright grain bowls" },
  { image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=960&q=85", alt: "Creamy pasta with herbs", label: "Pasta comfort" },
  { image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=960&q=85", alt: "Berry smoothie in a glass", label: "Berry smoothies" },
  { image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=960&q=85", alt: "Iced coffee on a table", label: "Slow coffee moments" },
  { image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=960&q=85", alt: "Chocolate dessert with berries", label: "Something sweet" },
];
const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;
const defaultProfile: Profile = { name: "", password: "", mobile: "", email: "", address: "Indiranagar, Bengaluru", deliveryTime: "30-35 min", emailVerified: false, phoneVerified: false };
const deliveryAreas = [
  ["Indiranagar", "30-35 min"], ["Koramangala", "35-40 min"], ["Whitefield", "45-55 min"], ["Jayanagar", "35-45 min"], ["HSR Layout", "35-45 min"], ["Malleshwaram", "30-40 min"], ["Hebbal", "45-55 min"], ["Electronic City", "50-60 min"],
];
const getDeliveryTime = (address: string) => deliveryAreas.find(([area]) => address.toLowerCase().includes(area.toLowerCase()))?.[1] ?? "40-50 min";
type SortOption = "relevance" | "price-low" | "price-high" | "time-low" | "time-high" | "rating-high" | "rating-low";

export function App() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [selectedRestaurant, setSelectedRestaurant] = useState<Restaurant | null>(null);
  const [cart, setCart] = useState<Record<string, { item: MenuItem; quantity: number }>>({});
  const [favorites, setFavorites] = useState<string[]>(() => {
    try {
      return JSON.parse(window.localStorage.getItem("foodflow-favorites") ?? "[]") as string[];
    } catch {
      return [];
    }
  });
  const [panel, setPanel] = useState<"login" | "cart" | "favorites" | "address" | "profile" | "checkout" | "success" | null>(null);
  const [profile, setProfile] = useState<Profile>(() => { try { return { ...defaultProfile, ...JSON.parse(window.localStorage.getItem("foodflow-profile") ?? "{}") }; } catch { return defaultProfile; } });
  const [loggedIn, setLoggedIn] = useState(() => window.localStorage.getItem("foodflow-logged-in") === "true");
  const [profileDraft, setProfileDraft] = useState<Profile>(profile);
  const [addressDraft, setAddressDraft] = useState(profile.address);
  const [addressTime, setAddressTime] = useState(profile.deliveryTime);
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>("card");
  const [otpStep, setOtpStep] = useState<"form" | "verify" | null>(null);
  const [otpCodes, setOtpCodes] = useState({ email: "", phone: "" });
  const [otpInputs, setOtpInputs] = useState({ email: "", phone: "" });
  const [otpError, setOtpError] = useState({ email: false, phone: false });
  const [cartNotice, setCartNotice] = useState<string | null>(null);
  const [sortOption, setSortOption] = useState<SortOption>("relevance");
  const [hasStarted, setHasStarted] = useState(false);
  const [portalSlide, setPortalSlide] = useState(0);
  const [vegMode, setVegMode] = useState(false);

  useEffect(() => {
    if (hasStarted) return;
    const timer = window.setInterval(() => setPortalSlide((current) => (current + 1) % portalSlides.length), 3200);
    return () => window.clearInterval(timer);
  }, [hasStarted]);

  useEffect(() => {
    window.localStorage.setItem("foodflow-favorites", JSON.stringify(favorites));
  }, [favorites]);

  useEffect(() => {
    window.localStorage.setItem("foodflow-profile", JSON.stringify(profile));
    window.localStorage.setItem("foodflow-logged-in", String(loggedIn));
  }, [loggedIn, profile]);

  const visibleRestaurants = useMemo(() => {
    const filtered = restaurants.filter((restaurant) => {
    const text = `${restaurant.name} ${restaurant.cuisine} ${restaurant.neighborhood} ${restaurant.menu.map((item) => item.name).join(" ")}`.toLowerCase();
    return (!query || text.includes(query.toLowerCase())) && (category === "All" || restaurant.cuisine.toLowerCase().includes(category.toLowerCase())) && (!vegMode || restaurant.menu.every((item) => item.vegetarian));
    });
    const averagePrice = (restaurant: Restaurant) => restaurant.menu.reduce((sum, item) => sum + item.price, 0) / restaurant.menu.length;
    return [...filtered].sort((left, right) => {
      if (sortOption === "price-low") return averagePrice(left) - averagePrice(right);
      if (sortOption === "price-high") return averagePrice(right) - averagePrice(left);
      if (sortOption === "time-low") return Number.parseInt(left.time) - Number.parseInt(right.time);
      if (sortOption === "time-high") return Number.parseInt(right.time) - Number.parseInt(left.time);
      if (sortOption === "rating-high") return Number.parseFloat(right.rating) - Number.parseFloat(left.rating);
      if (sortOption === "rating-low") return Number.parseFloat(left.rating) - Number.parseFloat(right.rating);
      return Number.parseFloat(right.rating) - Number.parseFloat(left.rating);
    });
  }, [category, query, sortOption, vegMode]);
  const cartItems = Object.values(cart);
  const subtotal = cartItems.reduce((total, entry) => total + entry.item.price * entry.quantity, 0);
  const deliveryFee = subtotal === 0 || subtotal >= 499 ? 0 : 39;
  const tax = Math.round(subtotal * 0.05);
  const total = subtotal + deliveryFee + tax;
  const location = profile.address;
  const deliveryTime = profile.deliveryTime;

  function addToCart(item: MenuItem) {
    setCart((current) => ({ ...current, [item.id]: { item, quantity: (current[item.id]?.quantity ?? 0) + 1 } }));
    setCartNotice(`${item.name} added to cart`);
    window.setTimeout(() => setCartNotice(null), 2200);
  }
  function changeQuantity(id: string, delta: number) { setCart((current) => { const next = { ...current }; const entry = next[id]; if (!entry) return current; if (entry.quantity + delta < 1) delete next[id]; else next[id] = { ...entry, quantity: entry.quantity + delta }; return next; }); }
  function openAddressEditor() { setAddressDraft(profile.address); setAddressTime(profile.deliveryTime); setPanel("address"); }
  function saveAddress() { const cleanAddress = addressDraft.trim().replace(/,?\s*Bengaluru$/i, ""); if (!cleanAddress) return; setProfile((current) => ({ ...current, address: `${cleanAddress}, Bengaluru`, deliveryTime: getDeliveryTime(cleanAddress) || addressTime })); setPanel(null); }
  function startLogin() { setProfileDraft(profile); setOtpStep("form"); setPanel("login"); }
  function sendVerificationCodes() { const emailCode = String(Math.floor(100000 + Math.random() * 900000)); const phoneCode = String(Math.floor(100000 + Math.random() * 900000)); setOtpCodes((current) => ({ email: otpError.email ? emailCode : current.email || emailCode, phone: otpError.phone ? phoneCode : current.phone || phoneCode })); setOtpInputs((current) => ({ email: otpError.email ? "" : current.email, phone: otpError.phone ? "" : current.phone })); setOtpError((current) => ({ email: false, phone: false })); setOtpStep("verify"); }
  function resendOtp(channel: "email" | "phone") { const nextCode = String(Math.floor(100000 + Math.random() * 900000)); setOtpCodes((current) => channel === "email" ? { ...current, email: nextCode } : { ...current, phone: nextCode }); setOtpInputs((current) => channel === "email" ? { ...current, email: "" } : { ...current, phone: "" }); setOtpError((current) => channel === "email" ? { ...current, email: false } : { ...current, phone: false }); }
  function verifyProfile() { const nextError = { email: otpInputs.email !== otpCodes.email, phone: otpInputs.phone !== otpCodes.phone }; if (nextError.email || nextError.phone) { setOtpError(nextError); return; } const nextProfile = { ...profileDraft, address: profile.address, deliveryTime: profile.deliveryTime, emailVerified: true, phoneVerified: true }; setProfile(nextProfile); setLoggedIn(true); setOtpStep(null); setPanel(null); }
  function closeOverlays() { setPanel(null); setSelectedRestaurant(null); setOtpStep(null); }

  if (!hasStarted) return <main className="welcome-portal"><div className="portal-glow glow-one" /><div className="portal-glow glow-two" /><div className="portal-content"><div className="portal-brand"><span className="brand-mark"><Utensils size={19} /></span><span>FOODFLOW</span></div><span className="portal-kicker"><Sparkles size={14} /> Bengaluru, served beautifully</span><h1>Discover.<br /><em>Order.</em><br />Enjoy.</h1><p>Local favorites, iconic kitchens, and your next great meal are closer than you think.</p><button className="start-button" onClick={() => setHasStarted(true)}>Get Started <ArrowRight size={19} /></button><small>Curated restaurants across Bengaluru</small></div><div className="portal-visual" aria-label="Food highlights slideshow"><div className="portal-ring ring-one" /><div className="portal-ring ring-two" /><div className="portal-slide-frame"><img key={portalSlides[portalSlide].image} src={portalSlides[portalSlide].image} alt={portalSlides[portalSlide].alt} /></div><div className="portal-badge"><Star size={14} fill="currentColor" /> 4.8 local favorites</div><div className="portal-dots" aria-label="Choose a featured dish">{portalSlides.map((slide, index) => <button key={slide.image} className={index === portalSlide ? "active" : ""} onClick={() => setPortalSlide(index)} aria-label={`Show featured image ${index + 1}`} aria-current={index === portalSlide ? "true" : undefined} />)}</div></div><div className="portal-footer"><span>FOODFLOW</span><span>Discover. Order. Track. Enjoy.</span></div></main>;

  return <main className="app-shell">
    <nav className="topbar"><button className="brand" onClick={closeOverlays}><span className="brand-mark"><Utensils size={17} /></span><span>FOODFLOW</span></button><button className="location-button" onClick={openAddressEditor}><MapPin size={17} /><span><small>Delivering to · {deliveryTime}</small>{location}</span><ChevronDown size={16} /></button><div className="nav-actions"><label className={vegMode ? "veg-toggle active" : "veg-toggle"}><input type="checkbox" checked={vegMode} onChange={(event) => setVegMode(event.target.checked)} /><span className="toggle-track"><span /></span><span>Veg mode</span></label><button className="icon-button" aria-label="Favorites" onClick={() => setPanel("favorites")}><Heart size={19} fill={favorites.length > 0 ? "currentColor" : "none"} /></button><button className="cart-button" onClick={() => setPanel("cart")}><ShoppingBag size={18} /><span>Cart</span>{cartItems.length > 0 && <b>{cartItems.reduce((count, entry) => count + entry.quantity, 0)}</b>}</button><button className="account-button" onClick={() => loggedIn ? setPanel("profile") : startLogin()}><UserRound size={16} />{loggedIn ? profile.name : "Log in"}</button></div></nav>

    {cartNotice && <div className="cart-toast" role="status"><span className="toast-check"><Check size={15} /></span><span><strong>Added to cart</strong><small>{cartNotice.replace(" added to cart", "")}</small></span><button onClick={() => setPanel("cart")}>View cart</button></div>}

    <section className="hero"><div className="hero-copy"><span className="eyebrow"><Store size={14} /> Bengaluru's local kitchens</span><h1>Good food,<br /><em>good mood.</em></h1><p>Order from the restaurants you know and love across Bengaluru, delivered to your door.</p><label className="search-box"><Search size={20} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search restaurants, dishes or cuisines" /><kbd>/</kbd></label></div><div className="hero-visual"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="plate"><img src={foodImages.biryani} alt="Bangalore biryani" /></div><div className="floating-note"><Star size={15} fill="currentColor" /> <strong>4.8</strong><span>from Bengaluru locals</span></div></div></section>

    <section className="trust-strip"><span><Check size={15} /> Curated Bangalore restaurants</span><span><Check size={15} /> Transparent checkout</span><span><Check size={15} /> Live order-ready flow</span></section>
    <section className="content-section category-section"><div className="section-heading"><div><span className="section-kicker">Explore Bengaluru</span><h2>What are you in the mood for?</h2></div><span className="result-count">{visibleRestaurants.length} restaurants</span></div><div className="category-row">{categories.map(([name, icon]) => <button key={name} className={category === name ? "category active" : "category"} onClick={() => setCategory(name)}><span>{icon}</span><small>{name === "All" ? "Everything" : name}</small></button>)}</div></section>

    <section className="content-section"><div className="section-heading"><div><span className="section-kicker">Verified local names</span><h2>Restaurants near {location.split(",")[0]}</h2></div><label className="sort-control"><Clock3 size={15} /><span>Sort by</span><select aria-label="Sort restaurants" value={sortOption} onChange={(event) => setSortOption(event.target.value as SortOption)}><option value="relevance">Recommended</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="time-low">Delivery: fastest first</option><option value="time-high">Delivery: slowest first</option><option value="rating-high">Rating: high to low</option><option value="rating-low">Rating: low to high</option></select><ChevronDown size={14} /></label></div><div className="restaurant-grid">{visibleRestaurants.map((restaurant) => <article className="restaurant-card" key={restaurant.id}><button className="card-image" onClick={() => setSelectedRestaurant(restaurant)}><img src={restaurant.image} alt={restaurant.name} /><span className="offer-tag">{restaurant.tag}</span></button><div className="card-body"><div className="card-title"><button className="restaurant-name" onClick={() => setSelectedRestaurant(restaurant)}>{restaurant.name}</button><span className="rating"><Star size={13} fill="currentColor" /> {restaurant.rating}</span></div><p>{restaurant.cuisine} · {restaurant.neighborhood}</p><div className="card-meta"><span>{restaurant.time}</span><button className={favorites.includes(restaurant.id) ? "favorite inline active" : "favorite inline"} onClick={() => setFavorites((current) => current.includes(restaurant.id) ? current.filter((id) => id !== restaurant.id) : [...current, restaurant.id])} aria-label={`Favorite ${restaurant.name}`}><Heart size={16} fill={favorites.includes(restaurant.id) ? "currentColor" : "none"} /></button><button className="view-menu" onClick={() => setSelectedRestaurant(restaurant)}>View menu <ArrowRight size={14} /></button></div></div></article>)}</div>{visibleRestaurants.length === 0 && <div className="empty-state"><Search size={25} /><h3>No matches yet</h3><p>Try a different restaurant, dish, or neighborhood.</p></div>}</section>
    {cartItems.length > 0 && <div className="live-cart" role="region" aria-label="Live cart summary"><div className="live-cart-icon"><ShoppingBag size={18} /></div><div className="live-cart-copy"><strong>{cartItems.reduce((count, entry) => count + entry.quantity, 0)} items in your cart</strong><span>{cartItems.slice(0, 2).map(({ item, quantity }) => `${quantity} × ${item.name}`).join(" · ")}{cartItems.length > 2 ? " · +more" : ""}</span></div><b>{money(subtotal)}</b><button onClick={() => setPanel("cart")}>View cart <ArrowRight size={15} /></button></div>}
    <section className="content-section recommendation"><div><span className="section-kicker">Your taste profile</span><h2>Because you liked <em>Masala Dosa</em></h2><p>More crisp, comforting South Indian picks from kitchens nearby.</p></div><button className="outline-button" onClick={() => { setCategory("South Indian"); window.scrollTo({ top: 650, behavior: "smooth" }); }}>View recommendations <ArrowRight size={16} /></button></section>
    <footer><div className="brand"><span className="brand-mark"><Utensils size={15} /></span><span>FOODFLOW</span></div><span>Discover. Order. Track. Enjoy.</span><span>© 2026 Foodflow · Demo ordering experience</span></footer>

    {selectedRestaurant && <div className="overlay" onClick={closeOverlays}><section className="menu-panel" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={closeOverlays} aria-label="Close menu"><X size={20} /></button><img className="menu-cover" src={selectedRestaurant.image} alt="" /><div className="menu-header"><span className="section-kicker">{selectedRestaurant.neighborhood}, Bengaluru</span><h2>{selectedRestaurant.name}</h2><p>{selectedRestaurant.cuisine} · <Star size={14} fill="currentColor" /> {selectedRestaurant.rating} · {selectedRestaurant.time}</p></div><div className="menu-list">{selectedRestaurant.menu.map((item) => <article className="menu-item" key={item.id}><img src={item.image} alt="" /><div><h3>{item.name} {item.vegetarian && <span className="veg-dot">VEG</span>}</h3><p>{item.description}</p><strong>{money(item.price)}</strong></div><button className="add-button" onClick={() => addToCart(item)}><Plus size={16} /> Add</button></article>)}</div></section></div>}
    {panel === "favorites" && <div className="overlay" onClick={closeOverlays}><aside className="side-panel" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><span className="section-kicker">Saved for later</span><h2>Favorites</h2></div><button className="close-button" onClick={closeOverlays} aria-label="Close favorites"><X size={20} /></button></div>{favorites.length === 0 ? <div className="empty-panel"><Heart size={30} /><h3>No favorites yet</h3><p>Tap the heart on a restaurant to save it here.</p></div> : <div className="favorites-list">{favorites.map((id) => restaurants.find((restaurant) => restaurant.id === id)).filter((restaurant): restaurant is Restaurant => Boolean(restaurant)).map((restaurant) => <article className="favorite-line" key={restaurant.id}><img src={restaurant.image} alt={restaurant.name} /><div><strong>{restaurant.name}</strong><span>{restaurant.cuisine} · {restaurant.neighborhood}</span></div><button className="favorite-remove" onClick={() => setFavorites((current) => current.filter((favoriteId) => favoriteId !== restaurant.id))} aria-label={`Remove ${restaurant.name} from favorites`}><Heart size={16} fill="currentColor" /></button><button className="view-menu" onClick={() => { setSelectedRestaurant(restaurant); setPanel(null); }}>View menu <ArrowRight size={14} /></button></article>)}</div>}</aside></div>}
    {panel === "cart" && <div className="overlay" onClick={closeOverlays}><aside className="side-panel" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><span className="section-kicker">Your order</span><h2>Cart</h2></div><button className="close-button" onClick={closeOverlays} aria-label="Close cart"><X size={20} /></button></div>{cartItems.length === 0 ? <div className="empty-panel"><ShoppingBag size={30} /><h3>Your cart is waiting</h3><p>Choose a dish from a Bengaluru kitchen to get started.</p></div> : <><div className="cart-list">{cartItems.map(({ item, quantity }) => <div className="cart-line" key={item.id}><div><strong>{item.name}</strong><span>{money(item.price)} each</span></div><div className="quantity"><button onClick={() => changeQuantity(item.id, -1)} aria-label="Decrease quantity"><Minus size={14} /></button><b>{quantity}</b><button onClick={() => changeQuantity(item.id, 1)} aria-label="Increase quantity"><Plus size={14} /></button></div></div>)}</div><div className="bill"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Delivery fee</span><b>{deliveryFee ? money(deliveryFee) : "FREE"}</b></div><div><span>Taxes (5%)</span><b>{money(tax)}</b></div><div className="bill-total"><span>Total</span><b>{money(total)}</b></div></div><button className="primary-button" onClick={() => setPanel("checkout")}>Continue to checkout <ArrowRight size={17} /></button></>}</aside></div>}
    {panel === "address" && <div className="overlay" onClick={closeOverlays}><section className="auth-panel address-editor" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={closeOverlays} aria-label="Close address editor"><X size={20} /></button><span className="brand-mark"><MapPin size={17} /></span><h2>Delivery address</h2><p>Enter any neighborhood, street, or landmark in Bengaluru.</p><input className="form-input" value={addressDraft} onChange={(event) => setAddressDraft(event.target.value)} placeholder="Address or neighborhood" /><select className="form-input" value={addressTime} onChange={(event) => setAddressTime(event.target.value)}>{deliveryAreas.map(([area, time]) => <option key={area} value={time}>{area} · {time}</option>)}</select><button className="primary-button" onClick={saveAddress}>Save delivery address <Check size={17} /></button></section></div>}
    {panel === "login" && <div className="overlay" onClick={closeOverlays}><section className="auth-panel" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={closeOverlays} aria-label="Close login"><X size={20} /></button><span className="brand-mark"><UserRound size={17} /></span>{otpStep === "form" ? <><h2>Create your profile</h2><p>Enter your details. We will verify your email and phone with demo OTPs.</p><input className="form-input" value={profileDraft.name} onChange={(event) => setProfileDraft({ ...profileDraft, name: event.target.value })} placeholder="Full name" /><input className="form-input" value={profileDraft.mobile} onChange={(event) => setProfileDraft({ ...profileDraft, mobile: event.target.value })} placeholder="Mobile number" type="tel" /><input className="form-input" value={profileDraft.email} onChange={(event) => setProfileDraft({ ...profileDraft, email: event.target.value })} placeholder="Email address" type="email" /><input className="form-input" value={profileDraft.password} onChange={(event) => setProfileDraft({ ...profileDraft, password: event.target.value })} placeholder="Password" type="password" /><button className="primary-button" disabled={!profileDraft.name || !profileDraft.mobile || !profileDraft.email || !profileDraft.password} onClick={sendVerificationCodes}>Send verification OTPs <ArrowRight size={17} /></button></> : <><h2>Verify your profile</h2><p>Enter the six-digit codes sent to your email and phone.</p><div className="demo-otp-note">Demo email OTP: <b>{otpCodes.email}</b><br />Demo phone OTP: <b>{otpCodes.phone}</b></div><label className="otp-field">Email OTP<input className={otpError.email ? "form-input invalid" : "form-input"} value={otpInputs.email} onChange={(event) => { setOtpInputs({ ...otpInputs, email: event.target.value }); setOtpError({ ...otpError, email: false }); }} placeholder="Email OTP" inputMode="numeric" />{otpError.email && <small className="otp-error">Invalid OTP for email. <button onClick={sendVerificationCodes}>Resend OTP</button></small>}</label><label className="otp-field">Mobile OTP<input className={otpError.phone ? "form-input invalid" : "form-input"} value={otpInputs.phone} onChange={(event) => { setOtpInputs({ ...otpInputs, phone: event.target.value }); setOtpError({ ...otpError, phone: false }); }} placeholder="Mobile OTP" inputMode="numeric" />{otpError.phone && <small className="otp-error">Invalid OTP for mobile number. <button onClick={sendVerificationCodes}>Resend OTP</button></small>}</label><button className="primary-button" onClick={verifyProfile}>Verify and continue <Check size={17} /></button></>}<span className="auth-note">Demo mode · password is stored locally for this prototype only.</span></section></div>}
    {panel === "profile" && <div className="overlay" onClick={closeOverlays}><section className="auth-panel profile-panel" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={closeOverlays} aria-label="Close profile"><X size={20} /></button><span className="brand-mark"><UserRound size={17} /></span><h2>Your profile</h2><div className="profile-fields"><label>Name<input className="form-input" value={profileDraft.name} onChange={(event) => setProfileDraft({ ...profileDraft, name: event.target.value })} /></label><label>Password<input className="form-input" value={profileDraft.password} onChange={(event) => setProfileDraft({ ...profileDraft, password: event.target.value })} type="password" /></label><label>Mobile number<input className="form-input" value={profileDraft.mobile} onChange={(event) => setProfileDraft({ ...profileDraft, mobile: event.target.value })} type="tel" /></label><label>Email address<input className="form-input" value={profileDraft.email} onChange={(event) => setProfileDraft({ ...profileDraft, email: event.target.value })} type="email" /></label><label>Default delivery address<input className="form-input" value={profileDraft.address} onChange={(event) => setProfileDraft({ ...profileDraft, address: event.target.value })} /></label></div><div className="profile-summary">Password: {profile.password ? `••••${profile.password.slice(-4)}` : "Not set"}<br />Email: {profile.emailVerified ? "Verified" : "Not verified"} · Phone: {profile.phoneVerified ? "Verified" : "Not verified"}</div><button className="primary-button" onClick={() => { const nextAddress = profileDraft.address.includes("Bengaluru") ? profileDraft.address : `${profileDraft.address}, Bengaluru`; setProfile({ ...profileDraft, address: nextAddress, deliveryTime: getDeliveryTime(nextAddress) }); setPanel(null); }}>Save profile changes <Check size={17} /></button><button className="text-button profile-logout" onClick={() => { setLoggedIn(false); setPanel(null); }}>Log out</button></section></div>}
    {panel === "checkout" && <div className="overlay" onClick={closeOverlays}><section className="checkout-panel" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><span className="section-kicker">Final step</span><h2>Checkout</h2></div><button className="close-button" onClick={closeOverlays} aria-label="Close checkout"><X size={20} /></button></div><div className="stepper"><span className="done"><Check size={13} /> Address</span><span className="active-step">2 Payment</span><span>3 Confirmation</span></div><div className="address-card"><MapPin size={18} /><div><strong>Deliver to home</strong><p>{location} · {deliveryTime}</p></div><button onClick={openAddressEditor}>Change</button></div><h3>Choose payment method</h3><div className="payment-options"><button className={paymentMethod === "card" ? "payment-option selected" : "payment-option"} onClick={() => setPaymentMethod("card")}><CreditCard size={20} /><span><b>Card</b><small>Visa, Mastercard, RuPay</small></span>{paymentMethod === "card" && <Check size={17} />}</button><button className={paymentMethod === "upi" ? "payment-option selected" : "payment-option"} onClick={() => setPaymentMethod("upi")}><Smartphone size={20} /><span><b>UPI</b><small>Google Pay, PhonePe, Paytm</small></span>{paymentMethod === "upi" && <Check size={17} />}</button><button className={paymentMethod === "cash" ? "payment-option selected" : "payment-option"} onClick={() => setPaymentMethod("cash")}><span className="cash-icon">₹</span><span><b>Cash on delivery</b><small>Pay when your food arrives</small></span>{paymentMethod === "cash" && <Check size={17} />}</button></div><div className="checkout-total"><span>Payable now</span><strong>{money(total)}</strong></div><button className="primary-button" onClick={() => setPanel("success")}>Place demo order <ArrowRight size={17} /></button><small className="demo-disclaimer">This is a development checkout. No real payment is processed.</small></section></div>}
    {panel === "success" && <div className="overlay"><section className="success-panel"><div className="success-icon"><Check size={28} /></div><span className="section-kicker">Order received</span><h2>Your kitchen is on it.</h2><p>Your order has been placed for delivery to {location}.</p><div className="tracking-line"><span className="active-dot" /><span /><span /><span /><span /></div><div className="tracking-labels"><b>Confirmed</b><span>Preparing</span><span>On the way</span><span>Delivered</span></div><button className="primary-button" onClick={() => { setCart({}); closeOverlays(); }}>Back to browsing</button></section></div>}
  </main>;
}
