import { useMemo, useState } from "react";
import { ArrowRight, Check, ChevronDown, Clock3, CreditCard, Heart, MapPin, Minus, Plus, Search, ShoppingBag, Smartphone, Star, Store, UserRound, Utensils, X } from "lucide-react";

type MenuItem = { id: string; name: string; description: string; price: number; vegetarian: boolean; image: string };
type Restaurant = { id: string; name: string; neighborhood: string; cuisine: string; rating: string; time: string; tag: string; image: string; menu: MenuItem[] };

const foodImages = {
  biryani: "/food/biryani.jpg",
  dosa: "/food/dosa.jpg",
  thali: "/food/thali.jpg",
  burger: "/food/burger.jpg",
  pizza: "/food/pizza.jpg",
};

const restaurants: Restaurant[] = [
  { id: "meghana", name: "Meghana Foods", neighborhood: "Indiranagar", cuisine: "Andhra · Biryani", rating: "4.6", time: "32 min", tag: "Bestseller", image: foodImages.biryani, menu: [{ id: "m1", name: "Chicken Biryani", description: "Aromatic basmati rice, tender chicken and Meghana's signature masala.", price: 289, vegetarian: false, image: foodImages.biryani }, { id: "m2", name: "Paneer Biryani", description: "Fragrant rice layered with spiced paneer and fried onions.", price: 249, vegetarian: true, image: foodImages.biryani }, { id: "m3", name: "Chicken Boneless", description: "Andhra-style boneless chicken tossed in a fiery masala.", price: 329, vegetarian: false, image: foodImages.thali }] },
  { id: "nagarjuna", name: "Nagarjuna", neighborhood: "Residency Road", cuisine: "Andhra · Meals", rating: "4.5", time: "38 min", tag: "Iconic since 1984", image: foodImages.thali, menu: [{ id: "n1", name: "Nagarjuna Special Meals", description: "Unlimited Andhra thali with rice, curries, rasam and dessert.", price: 320, vegetarian: false, image: foodImages.thali }, { id: "n2", name: "Paneer Pepper Fry", description: "Peppery paneer with curry leaves and roasted spices.", price: 260, vegetarian: true, image: foodImages.thali }] },
  { id: "mtr", name: "MTR 1924", neighborhood: "Lalbagh Road", cuisine: "South Indian · Vegetarian", rating: "4.7", time: "27 min", tag: "Pure veg", image: foodImages.dosa, menu: [{ id: "t1", name: "Rava Idli", description: "MTR's famous steamed semolina idli with ghee and chutney.", price: 95, vegetarian: true, image: foodImages.dosa }, { id: "t2", name: "Masala Dosa", description: "Golden dosa, potato palya, sambar and coconut chutney.", price: 145, vegetarian: true, image: foodImages.dosa }] },
  { id: "truffles", name: "Truffles", neighborhood: "Koramangala", cuisine: "Burgers · American", rating: "4.6", time: "35 min", tag: "20% off", image: foodImages.burger, menu: [{ id: "f1", name: "All American Cheese Burger", description: "Grilled patty, cheddar, lettuce, tomato and house sauce.", price: 295, vegetarian: false, image: foodImages.burger }, { id: "f2", name: "Veg Extravaganza Burger", description: "Crispy veg patty, cheese, jalapenos and signature sauce.", price: 245, vegetarian: true, image: foodImages.burger }] },
  { id: "empire", name: "Empire Restaurant", neighborhood: "Brigade Road", cuisine: "North Indian · Kebabs", rating: "4.4", time: "30 min", tag: "Late night", image: foodImages.thali, menu: [{ id: "e1", name: "Empire Chicken Kebab", description: "Char-grilled chicken marinated in warm Indian spices.", price: 280, vegetarian: false, image: foodImages.thali }, { id: "e2", name: "Butter Naan & Paneer", description: "Soft butter naan with creamy paneer gravy.", price: 230, vegetarian: true, image: foodImages.thali }] },
  { id: "chianti", name: "Chianti", neighborhood: "St. Marks Road", cuisine: "Italian · Pizza", rating: "4.5", time: "41 min", tag: "Free delivery", image: foodImages.pizza, menu: [{ id: "c1", name: "Margherita Pizza", description: "San Marzano tomato, fresh mozzarella, basil and olive oil.", price: 420, vegetarian: true, image: foodImages.pizza }, { id: "c2", name: "Chicken Pesto Pizza", description: "Roasted chicken, basil pesto, mozzarella and cherry tomato.", price: 510, vegetarian: false, image: foodImages.pizza }] },
  { id: "biriyani-zone", name: "Biryani Zone", neighborhood: "HSR Layout", cuisine: "Biryani · Mughlai", rating: "4.3", time: "34 min", tag: "Combo meals", image: foodImages.biryani, menu: [{ id: "bz1", name: "Hyderabadi Chicken Biryani", description: "Long-grain rice, slow-cooked chicken and saffron-spiced gravy.", price: 259, vegetarian: false, image: foodImages.biryani }, { id: "bz2", name: "Mushroom Biryani", description: "Basmati rice, roasted mushrooms and fragrant whole spices.", price: 219, vegetarian: true, image: foodImages.biryani }] },
  { id: "udupi", name: "Udupi Garden", neighborhood: "BTM Layout", cuisine: "South Indian · Vegetarian", rating: "4.4", time: "25 min", tag: "Pure veg", image: foodImages.dosa, menu: [{ id: "u1", name: "Set Dosa", description: "Three soft dosas with vegetable saagu and coconut chutney.", price: 120, vegetarian: true, image: foodImages.dosa }, { id: "u2", name: "Bisibele Bath", description: "Classic Karnataka rice-lentil bowl with ghee and boondi.", price: 135, vegetarian: true, image: foodImages.thali }] },
  { id: "saarangi", name: "Saarangi", neighborhood: "Whitefield", cuisine: "North Indian · Kebabs", rating: "4.5", time: "42 min", tag: "Chef special", image: foodImages.thali, menu: [{ id: "s1", name: "Dal Makhani", description: "Slow-simmered black lentils finished with butter and cream.", price: 245, vegetarian: true, image: foodImages.thali }, { id: "s2", name: "Tandoori Chicken", description: "Yogurt-marinated chicken roasted in the tandoor.", price: 385, vegetarian: false, image: foodImages.thali }] },
  { id: "social", name: "Social", neighborhood: "Church Street", cuisine: "Café · Continental", rating: "4.4", time: "36 min", tag: "Trending", image: foodImages.burger, menu: [{ id: "so1", name: "Social Butter Chicken", description: "Creamy tomato butter chicken with toasted naan.", price: 340, vegetarian: false, image: foodImages.thali }, { id: "so2", name: "Loaded Veg Burger", description: "Crispy vegetable patty, lettuce and smoky house sauce.", price: 280, vegetarian: true, image: foodImages.burger }] },
  { id: "corner-house", name: "Corner House Ice Cream", neighborhood: "Jayanagar", cuisine: "Desserts · Ice Cream", rating: "4.8", time: "22 min", tag: "Sweet fix", image: foodImages.burger, menu: [{ id: "ch1", name: "Death By Chocolate", description: "Chocolate ice cream, brownie, sauce and chocolate flakes.", price: 220, vegetarian: true, image: foodImages.burger }, { id: "ch2", name: "Hot Chocolate Fudge", description: "Vanilla ice cream, warm fudge and roasted nuts.", price: 195, vegetarian: true, image: foodImages.burger }] },
  { id: "karama", name: "Karama Restaurant", neighborhood: "Frazer Town", cuisine: "Arabian · Kebabs", rating: "4.5", time: "39 min", tag: "Family feast", image: foodImages.thali, menu: [{ id: "k1", name: "Chicken Shawarma Plate", description: "Charcoal chicken, hummus, pita and garlic sauce.", price: 310, vegetarian: false, image: foodImages.thali }, { id: "k2", name: "Falafel Platter", description: "Crisp falafel with hummus, salad and warm pita.", price: 260, vegetarian: true, image: foodImages.thali }] },
  { id: "onyx", name: "The Fat Chef", neighborhood: "Malleshwaram", cuisine: "Pizza · Italian", rating: "4.6", time: "33 min", tag: "New on Foodflow", image: foodImages.pizza, menu: [{ id: "fc1", name: "Four Cheese Pizza", description: "Mozzarella, parmesan, cheddar and blue cheese on a crisp base.", price: 460, vegetarian: true, image: foodImages.pizza }, { id: "fc2", name: "Pepperoni Pizza", description: "Spiced pepperoni, mozzarella and oregano.", price: 520, vegetarian: false, image: foodImages.pizza }] },
];

const categories = [["All", "✦"], ["Biryani", "🍛"], ["Pizza", "🍕"], ["South Indian", "🥘"], ["Burgers", "🍔"], ["Desserts", "🍰"]];
const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;
type SortOption = "relevance" | "price-low" | "price-high" | "time-low" | "time-high" | "rating-high" | "rating-low";

export function App() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [selectedRestaurant, setSelectedRestaurant] = useState<Restaurant | null>(null);
  const [cart, setCart] = useState<Record<string, { item: MenuItem; quantity: number }>>({});
  const [favorites, setFavorites] = useState<string[]>([]);
  const [panel, setPanel] = useState<"login" | "cart" | "checkout" | "success" | null>(null);
  const [location, setLocation] = useState("Indiranagar, Bengaluru");
  const [loggedIn, setLoggedIn] = useState(false);
  const [cartNotice, setCartNotice] = useState<string | null>(null);
  const [sortOption, setSortOption] = useState<SortOption>("relevance");

  const visibleRestaurants = useMemo(() => {
    const filtered = restaurants.filter((restaurant) => {
    const text = `${restaurant.name} ${restaurant.cuisine} ${restaurant.neighborhood} ${restaurant.menu.map((item) => item.name).join(" ")}`.toLowerCase();
    return (!query || text.includes(query.toLowerCase())) && (category === "All" || restaurant.cuisine.toLowerCase().includes(category.toLowerCase()));
    });
    const averagePrice = (restaurant: Restaurant) => restaurant.menu.reduce((sum, item) => sum + item.price, 0) / restaurant.menu.length;
    return [...filtered].sort((left, right) => {
      if (sortOption === "price-low") return averagePrice(left) - averagePrice(right);
      if (sortOption === "price-high") return averagePrice(right) - averagePrice(left);
      if (sortOption === "time-low") return Number.parseInt(left.time) - Number.parseInt(right.time);
      if (sortOption === "time-high") return Number.parseInt(right.time) - Number.parseInt(left.time);
      if (sortOption === "rating-high") return Number.parseFloat(right.rating) - Number.parseFloat(left.rating);
      if (sortOption === "rating-low") return Number.parseFloat(left.rating) - Number.parseFloat(right.rating);
      return Number.parseFloat(right.rating) - Number.parseFloat(left.rating);
    });
  }, [category, query, sortOption]);
  const cartItems = Object.values(cart);
  const subtotal = cartItems.reduce((total, entry) => total + entry.item.price * entry.quantity, 0);
  const deliveryFee = subtotal === 0 || subtotal >= 499 ? 0 : 39;
  const tax = Math.round(subtotal * 0.05);
  const total = subtotal + deliveryFee + tax;

  function addToCart(item: MenuItem) {
    setCart((current) => ({ ...current, [item.id]: { item, quantity: (current[item.id]?.quantity ?? 0) + 1 } }));
    setCartNotice(`${item.name} added to cart`);
    window.setTimeout(() => setCartNotice(null), 2200);
  }
  function changeQuantity(id: string, delta: number) { setCart((current) => { const next = { ...current }; const entry = next[id]; if (!entry) return current; if (entry.quantity + delta < 1) delete next[id]; else next[id] = { ...entry, quantity: entry.quantity + delta }; return next; }); }
  function closeOverlays() { setPanel(null); setSelectedRestaurant(null); }

  return <main className="app-shell">
    <nav className="topbar"><button className="brand" onClick={closeOverlays}><span className="brand-mark"><Utensils size={17} /></span><span>FOODFLOW</span></button><button className="location-button"><MapPin size={17} /><span><small>Delivering to</small>{location}</span><ChevronDown size={16} /></button><div className="nav-actions"><button className="icon-button" aria-label="Favorites"><Heart size={19} /></button><button className="cart-button" onClick={() => setPanel("cart")}><ShoppingBag size={18} /><span>Cart</span>{cartItems.length > 0 && <b>{cartItems.reduce((count, entry) => count + entry.quantity, 0)}</b>}</button><button className="account-button" onClick={() => setPanel("login")}><UserRound size={16} />{loggedIn ? "Aarav" : "Log in"}</button></div></nav>

    {cartNotice && <div className="cart-toast" role="status"><span className="toast-check"><Check size={15} /></span><span><strong>Added to cart</strong><small>{cartNotice.replace(" added to cart", "")}</small></span><button onClick={() => setPanel("cart")}>View cart</button></div>}

    <section className="hero"><div className="hero-copy"><span className="eyebrow"><Store size={14} /> Bengaluru's local kitchens</span><h1>Good food,<br /><em>good mood.</em></h1><p>Order from the restaurants you know and love across Bengaluru, delivered to your door.</p><label className="search-box"><Search size={20} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search restaurants, dishes or cuisines" /><kbd>/</kbd></label></div><div className="hero-visual"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="plate"><img src={foodImages.biryani} alt="Bangalore biryani" /></div><div className="floating-note"><Star size={15} fill="currentColor" /> <strong>4.8</strong><span>from Bengaluru locals</span></div></div></section>

    <section className="trust-strip"><span><Check size={15} /> Curated Bangalore restaurants</span><span><Check size={15} /> Transparent checkout</span><span><Check size={15} /> Live order-ready flow</span></section>
    <section className="content-section category-section"><div className="section-heading"><div><span className="section-kicker">Explore Bengaluru</span><h2>What are you in the mood for?</h2></div><span className="result-count">{visibleRestaurants.length} restaurants</span></div><div className="category-row">{categories.map(([name, icon]) => <button key={name} className={category === name ? "category active" : "category"} onClick={() => setCategory(name)}><span>{icon}</span><small>{name === "All" ? "Everything" : name}</small></button>)}</div></section>

    <section className="content-section"><div className="section-heading"><div><span className="section-kicker">Verified local names</span><h2>Restaurants near {location.split(",")[0]}</h2></div><label className="sort-control"><Clock3 size={15} /><span>Sort by</span><select aria-label="Sort restaurants" value={sortOption} onChange={(event) => setSortOption(event.target.value as SortOption)}><option value="relevance">Recommended</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="time-low">Delivery: fastest first</option><option value="time-high">Delivery: slowest first</option><option value="rating-high">Rating: high to low</option><option value="rating-low">Rating: low to high</option></select><ChevronDown size={14} /></label></div><div className="restaurant-grid">{visibleRestaurants.map((restaurant) => <article className="restaurant-card" key={restaurant.id}><button className="card-image" onClick={() => setSelectedRestaurant(restaurant)}><img src={restaurant.image} alt={restaurant.name} /><span className="offer-tag">{restaurant.tag}</span></button><div className="card-body"><div className="card-title"><button className="restaurant-name" onClick={() => setSelectedRestaurant(restaurant)}>{restaurant.name}</button><span className="rating"><Star size={13} fill="currentColor" /> {restaurant.rating}</span></div><p>{restaurant.cuisine} · {restaurant.neighborhood}</p><div className="card-meta"><span>{restaurant.time}</span><button className={favorites.includes(restaurant.id) ? "favorite inline active" : "favorite inline"} onClick={() => setFavorites((current) => current.includes(restaurant.id) ? current.filter((id) => id !== restaurant.id) : [...current, restaurant.id])} aria-label={`Favorite ${restaurant.name}`}><Heart size={16} fill={favorites.includes(restaurant.id) ? "currentColor" : "none"} /></button><button className="view-menu" onClick={() => setSelectedRestaurant(restaurant)}>View menu <ArrowRight size={14} /></button></div></div></article>)}</div>{visibleRestaurants.length === 0 && <div className="empty-state"><Search size={25} /><h3>No matches yet</h3><p>Try a different restaurant, dish, or neighborhood.</p></div>}</section>
    {cartItems.length > 0 && <div className="live-cart" role="region" aria-label="Live cart summary"><div className="live-cart-icon"><ShoppingBag size={18} /></div><div className="live-cart-copy"><strong>{cartItems.reduce((count, entry) => count + entry.quantity, 0)} items in your cart</strong><span>{cartItems.slice(0, 2).map(({ item, quantity }) => `${quantity} × ${item.name}`).join(" · ")}{cartItems.length > 2 ? " · +more" : ""}</span></div><b>{money(subtotal)}</b><button onClick={() => setPanel("cart")}>View cart <ArrowRight size={15} /></button></div>}
    <section className="content-section recommendation"><div><span className="section-kicker">Your taste profile</span><h2>Because you liked <em>Masala Dosa</em></h2><p>More crisp, comforting South Indian picks from kitchens nearby.</p></div><button className="outline-button" onClick={() => { setCategory("South Indian"); window.scrollTo({ top: 650, behavior: "smooth" }); }}>View recommendations <ArrowRight size={16} /></button></section>
    <footer><div className="brand"><span className="brand-mark"><Utensils size={15} /></span><span>FOODFLOW</span></div><span>Discover. Order. Track. Enjoy.</span><span>© 2026 Foodflow · Demo ordering experience</span></footer>

    {selectedRestaurant && <div className="overlay" onClick={closeOverlays}><section className="menu-panel" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={closeOverlays} aria-label="Close menu"><X size={20} /></button><img className="menu-cover" src={selectedRestaurant.image} alt="" /><div className="menu-header"><span className="section-kicker">{selectedRestaurant.neighborhood}, Bengaluru</span><h2>{selectedRestaurant.name}</h2><p>{selectedRestaurant.cuisine} · <Star size={14} fill="currentColor" /> {selectedRestaurant.rating} · {selectedRestaurant.time}</p></div><div className="menu-list">{selectedRestaurant.menu.map((item) => <article className="menu-item" key={item.id}><img src={item.image} alt="" /><div><h3>{item.name} {item.vegetarian && <span className="veg-dot">VEG</span>}</h3><p>{item.description}</p><strong>{money(item.price)}</strong></div><button className="add-button" onClick={() => addToCart(item)}><Plus size={16} /> Add</button></article>)}</div></section></div>}
    {panel === "cart" && <div className="overlay" onClick={closeOverlays}><aside className="side-panel" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><span className="section-kicker">Your order</span><h2>Cart</h2></div><button className="close-button" onClick={closeOverlays} aria-label="Close cart"><X size={20} /></button></div>{cartItems.length === 0 ? <div className="empty-panel"><ShoppingBag size={30} /><h3>Your cart is waiting</h3><p>Choose a dish from a Bengaluru kitchen to get started.</p></div> : <><div className="cart-list">{cartItems.map(({ item, quantity }) => <div className="cart-line" key={item.id}><div><strong>{item.name}</strong><span>{money(item.price)} each</span></div><div className="quantity"><button onClick={() => changeQuantity(item.id, -1)} aria-label="Decrease quantity"><Minus size={14} /></button><b>{quantity}</b><button onClick={() => changeQuantity(item.id, 1)} aria-label="Increase quantity"><Plus size={14} /></button></div></div>)}</div><div className="bill"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Delivery fee</span><b>{deliveryFee ? money(deliveryFee) : "FREE"}</b></div><div><span>Taxes (5%)</span><b>{money(tax)}</b></div><div className="bill-total"><span>Total</span><b>{money(total)}</b></div></div><button className="primary-button" onClick={() => setPanel("checkout")}>Continue to checkout <ArrowRight size={17} /></button></>}</aside></div>}
    {panel === "login" && <div className="overlay" onClick={closeOverlays}><section className="auth-panel" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={closeOverlays} aria-label="Close login"><X size={20} /></button><span className="brand-mark"><Utensils size={17} /></span><h2>Welcome back</h2><p>Sign in to save addresses, reorder favorites, and track every delivery.</p><input className="form-input" placeholder="Email address" type="email" /><input className="form-input" placeholder="Password" type="password" /><button className="primary-button" onClick={() => { setLoggedIn(true); closeOverlays(); }}>Log in to Foodflow</button><span className="auth-note">Demo mode · no account or payment is charged</span></section></div>}
    {panel === "checkout" && <div className="overlay" onClick={closeOverlays}><section className="checkout-panel" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><span className="section-kicker">Final step</span><h2>Checkout</h2></div><button className="close-button" onClick={closeOverlays} aria-label="Close checkout"><X size={20} /></button></div><div className="stepper"><span className="done"><Check size={13} /> Address</span><span className="active-step">2 Payment</span><span>3 Confirmation</span></div><div className="address-card"><MapPin size={18} /><div><strong>Deliver to home</strong><p>{location}</p></div><button onClick={() => setLocation(location === "Indiranagar, Bengaluru" ? "Koramangala 5th Block, Bengaluru" : "Indiranagar, Bengaluru")}>Change</button></div><h3>Choose payment method</h3><div className="payment-options"><button className="payment-option selected"><CreditCard size={20} /><span><b>Card</b><small>Visa, Mastercard, RuPay</small></span><Check size={17} /></button><button className="payment-option"><Smartphone size={20} /><span><b>UPI</b><small>Google Pay, PhonePe, Paytm</small></span></button><button className="payment-option"><span className="cash-icon">₹</span><span><b>Cash on delivery</b><small>Pay when your food arrives</small></span></button></div><div className="checkout-total"><span>Payable now</span><strong>{money(total)}</strong></div><button className="primary-button" onClick={() => setPanel("success")}>Place demo order <ArrowRight size={17} /></button><small className="demo-disclaimer">This is a development checkout. No real payment is processed.</small></section></div>}
    {panel === "success" && <div className="overlay"><section className="success-panel"><div className="success-icon"><Check size={28} /></div><span className="section-kicker">Order received</span><h2>Your kitchen is on it.</h2><p>Your order has been placed for delivery to {location}.</p><div className="tracking-line"><span className="active-dot" /><span /><span /><span /><span /></div><div className="tracking-labels"><b>Confirmed</b><span>Preparing</span><span>On the way</span><span>Delivered</span></div><button className="primary-button" onClick={() => { setCart({}); closeOverlays(); }}>Back to browsing</button></section></div>}
  </main>;
}
